# Docker-compose to run database for local development porposes
version: '3.8'

services:

  mongodb:
    image: mongo:6.0
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data/db
    networks:
      - stock-network

  mongo-express:
    image: mongo-express
    container_name: stock-app-mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    env_file: .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: ${DATABASE_URL_FOR_EXPRESS}
      ME_CONFIG_OPTIONS_EDITORTHEME: "dracula"
    depends_on:
      - mongodb
    command: /bin/sh -c "sleep 10 && tini -- /docker-entrypoint.sh"
    networks:
      - stock-network

volumes:
  mongo:

networks:
    stock-network:
      driver: bridge
      name: stock-network
