site_name: Stock App
repo_url: https://github.com/Jeremiaszmacura/stock-app-backend
site_description: Application to analyse stock data
site_author: Jeremiasz Macura
docs_dir: docs
theme:
  name: readthedocs
nav:
  - Introduction: 'index.md'
