name: Lint code

on:
  push:

jobs:
  lint-code:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Lint with pylint
        run: |
          pip install pylint
          pylint --exit-zero backend
      - name: Lint with black
        run: |
          pip install black
          python -m black -l 120 --check backend
