name: Pre-commit - Backend

on:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run pre-commit
        run: |
          ls -lah
          pip install pre-commit==3.6.0
          pre-commit run -a
