name: Lint code

on:
  push:

jobs:
  lint-code:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Lint with pylint
        run: |
          pip install pre-commit==3.6.0
          pre-commit run -a
