name: Unit Tests - Backend

on:
  push:

jobs:
  unit-testing:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependecies
        run: |
          pip install -r requirements-dev.txt

      - name: Run unit tests
        run: python -m pytest .
