name: Unit Tests

on:
  push:

jobs:
  unit-testing:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'

      - name: Install dependecies
        run: |
          pip install -r backend/requirements-dev.txt

      - name: Run unit tests
        run: python -m pytest .
